name             'identities'
maintainer       'Jean-Francois Theroux'
maintainer_email 'me@failshell.io'
license          'MIT'
description      'Installs/Configures identities'
long_description 'Installs/Configures identities'
version          '0.1.0'
